#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <uplib.h>
#include <upsiglib.h>
#include <up_segment_io.h>

void print_options (void)
{
	fprintf (stderr,"options are:\n");
	fprintf (stderr,"     -o  outfile\n");
	fprintf (stderr,"     -p  patfile\n");
	fprintf (stderr,"     -s  string\n");
	fprintf (stderr,"     -i  index\n");
	fprintf (stderr,"     -l  level\n");
	fprintf (stderr,"     -F  first\n");
	fprintf (stderr,"     -L  last\n");
}

upsegQueryInfo *parse_args (int argc, char *argv[], char outfile[])
{
	int i;
	static upsegQueryInfo info;

	if (argc<2) {
		fprintf (stderr,"use: %s unipen-file [unipen-files] [options]!\n",argv[0]);
		print_options();
		exit(1);
	}

	/* set default values */

	upsegInitializeQueryInfo(&info);

	for (i=1;i<argc;i++) {
		if (strcmp(argv[i],"-s")==0) {
			i++;
			upsegAddQuery(&info,argv[i]);
		}
		else if (strcmp(argv[i],"-p")==0) {
			i++;
			upsegAddQueriesFromPatfile(&info,argv[i]);
		}
		else if (strcmp(argv[i],"-o")==0) {
			i++;
			strcpy(outfile,argv[i]);
		}
		else if (strcmp(argv[i],"-i")==0) {
			i++;
			info.index = atoi(argv[i]);
			printf ("index set to %d\n",info.index);
		}
		else if (strcmp(argv[i],"-l")==0) {
			i++;
			strcpy(info.level,argv[i]);
			fprintf (stderr,"level set to %s\n",info.level);
		}
		else if (strcmp(argv[i],"-F")==0) {
			i++;
			info.first = atoi(argv[i]);
			printf ("first set to %d\n",info.first);
		}
		else if (strcmp(argv[i],"-L")==0) {
			i++;
			info.last = atoi(argv[i]);
			fprintf (stderr,"last set to %d\n",info.last);
		}
		else {
			if (argv[i][0]=='-') {
				fprintf (stderr,"wrong option '%s'!\n",argv[i]);
				fprintf (stderr,"use: %s unipen-file epsfile [options]!\n",argv[0]);
				print_options();
				exit(1);
			}
			else
				upsegAddFile(&info,argv[i]);
		}
	}
	return &info;
}

void upread_print_header (FILE *fp_out, upsegQueryInfo *info, char *files, char *hierarchy)
{
	int i;
	char *key_entry;

#ifndef UR_VERSION
#define UR_VERSION "V3.0 March 1997 - L.Schomaker, L.Vuurpijl, G.Abbink  - NICI"
#endif

	fprintf (fp_out,".VERSION 1.0\n");
	fprintf (fp_out,"\n");
	fprintf (fp_out,".COMMENT\n");
	fprintf (fp_out,"UNIPEN file automatically generated by upread\n");
	fprintf (fp_out,"upread: %s\n",UR_VERSION);
	fprintf (fp_out,"\n");
	fprintf (fp_out,"The files from which .%s segments were extracted were:\n",info->level);
	for (i=0;i<info->nfiles;i++)
  		fprintf (fp_out,"   %s\n",info->files[i]);
	fprintf (fp_out,"\n");
	fprintf (fp_out,"The query used for selection was:\n");
	fprintf (fp_out,"   -l %s\n",info->level);
	for (i=0;i<info->nstrings;i++)
		fprintf (fp_out,"   -s %s\n",info->strings[i]);
	fprintf (fp_out,"\n");
	fprintf (fp_out,".SETUP\n");
	if ((key_entry=upGetArgument(info->pUnipen,".COORD",1))==NULL)
		exit(1);
	fprintf (fp_out,"%s\n",key_entry);
	fprintf (fp_out,".X_POINTS_PER_MM             50 \n");
	fprintf (fp_out,".Y_POINTS_PER_MM             50 \n");
	fprintf (fp_out,".POINTS_PER_SECOND          100\n");
	fprintf (fp_out,".HIERARCHY");
	if (strcmp(info->level,"*")==0) {
			fprintf (fp_out," %s",hierarchy);
	} else {
		fprintf (fp_out," %s",info->level);
	}
	fprintf (fp_out,"\n.START_SET\n");
	fprintf (fp_out,"\n");
}

int upread_print_segment (FILE *fp_out, int streamnr, char *level, char *name, sigCharStream *streams)
{
	int i,next_streamnr,last_samplenr;

	next_streamnr = streamnr+streams->nstreams-1;
	last_samplenr = streams->nsamples[streams->nstreams-1]-1;
	fprintf (fp_out,".SEGMENT %s %d:0-%d:%d OK \"%s\"\n"
		,level,streamnr,next_streamnr,last_samplenr,name);
	for (i=0;i<streams->nstreams;i++) {
		fprintf (fp_out,"%s\n",streams->streams[i]);
	}
	return next_streamnr+1;
}

int main (int argc, char *argv[])
{
	FILE *fp_out;
	int i;
	tUPEntry **entries;
	sigCharStream **streams;
	int nentries;
	upsegQueryInfo *query_info;
	char outfile[512];
	char **names;
	char **level_names;
	char *hierarchy;
	int streamnr;

	fprintf (stderr,"upread: %s\n",UR_VERSION);
	outfile[0] = '\0';
	query_info = parse_args(argc,argv,outfile);
	if (outfile[0]=='\0') {
		fprintf (stderr,"upread: output to stdout\n");
		fp_out = stdout;
	}
	else if ((fp_out=fopen(outfile,"r"))!=NULL) {
		fprintf (stderr,"outfile %s already exists!",outfile);
		exit(1);
	} else if ((fp_out=fopen(outfile,"w"))==NULL) {
		fprintf (stderr,"unable to open outfile %s!",outfile);
		exit(1);
	}

	entries = upsegGetEntriesWithStreams (query_info,&nentries
	                                                ,&names
	                                                ,&streams
																	,&level_names
																	,&hierarchy);
	fprintf (stderr,"got %d entries\n",nentries);
	if (nentries<=0) {
		fprintf (stderr,"no items fulfil your query!\n");
		exit(1);
	}
	upread_print_header (fp_out,query_info,argv[1],hierarchy);

	streamnr = 0;
	for (i=0;i<nentries;i++) {
		streamnr = upread_print_segment(fp_out,streamnr
		                     ,level_names[i],names[i],streams[i]);
		free(level_names[i]);
		free(names[i]);
		sigDeleteCharStream(streams[i]);
	}
	free(level_names);
	free(names);
	free(entries);
	fclose(fp_out);
	upDelUnipen(query_info->pUnipen);
	return 0;
}
